select i.ITEM_ID, i.ITEM_NAME, i.RARITY from ITEM_INFO i
inner join ITEM_TREE t on i.ITEM_ID = t.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY I.ITEM_ID DESC;